export type Template = {
  id: string;
  name: string;
  goal: string;
  emailCount: number;
  contentTypes: string[];
  layoutStyle: string;
  tone: string;
  tags: string[];
  emails: {
    dayOffset: number;
    purpose: string;
    contentType: string;
  }[];
};

export const TEMPLATES: Template[] = [
  {
    id: "saas-onboarding-classic",
    name: "SaaS Onboarding Classic",
    goal: "Activation",
    emailCount: 7,
    contentTypes: ["Text"],
    layoutStyle: "Standard",
    tone: "Helpful",
    tags: ["Onboarding", "SaaS", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome & Account Setup", contentType: "Text" },
      { dayOffset: 1, purpose: "Core Feature 1", contentType: "Text" },
      { dayOffset: 3, purpose: "Core Feature 2", contentType: "Text" },
      { dayOffset: 5, purpose: "Best Practices", contentType: "Text" },
      { dayOffset: 7, purpose: "Advanced Feature", contentType: "Text" },
      { dayOffset: 10, purpose: "Case Study", contentType: "Text" },
      { dayOffset: 14, purpose: "Feedback & Check-in", contentType: "Text" },
    ],
  },
  {
    id: "trial-to-paid",
    name: "Trial to Paid",
    goal: "Trial → Paid",
    emailCount: 5,
    contentTypes: ["Text", "CTA"],
    layoutStyle: "Action-Oriented",
    tone: "Persuasive",
    tags: ["Trial conversion", "SaaS", "All"],
    emails: [
      { dayOffset: 0, purpose: "Trial Start & Value Prop", contentType: "Text + CTA" },
      { dayOffset: 3, purpose: "Quick Win Tutorial", contentType: "Text + CTA" },
      { dayOffset: 7, purpose: "Mid-Trial Check-in & ROI", contentType: "Text + CTA" },
      { dayOffset: 12, purpose: "Trial Ending Soon Warning", contentType: "Text + CTA" },
      { dayOffset: 14, purpose: "Final Offer & Upgrade", contentType: "Text + CTA" },
    ],
  },
  {
    id: "feature-spotlight",
    name: "Feature Spotlight",
    goal: "Adoption",
    emailCount: 3,
    contentTypes: ["Text", "Hero Image"],
    layoutStyle: "Visual",
    tone: "Exciting",
    tags: ["Feature launch", "All"],
    emails: [
      { dayOffset: 0, purpose: "Big Announcement", contentType: "Text + Hero Image" },
      { dayOffset: 2, purpose: "How it Works / Use Case", contentType: "Text" },
      { dayOffset: 5, purpose: "Reminder & Social Proof", contentType: "Text + Hero Image" },
    ],
  },
  {
    id: "win-back-campaign",
    name: "Win-back Campaign",
    goal: "Re-engagement",
    emailCount: 4,
    contentTypes: ["Text"],
    layoutStyle: "Minimal",
    tone: "Empathetic",
    tags: ["Win-back", "All"],
    emails: [
      { dayOffset: 0, purpose: "We Miss You / Check-in", contentType: "Text" },
      { dayOffset: 7, purpose: "What's New Since You Left", contentType: "Text" },
      { dayOffset: 14, purpose: "Special Offer / Discount", contentType: "Text" },
      { dayOffset: 21, purpose: "Final Notice / Account Deletion", contentType: "Text" },
    ],
  },
  {
    id: "product-led-growth",
    name: "Product-led Growth",
    goal: "Activation",
    emailCount: 7,
    contentTypes: ["Text", "Screenshot"],
    layoutStyle: "Product-Focused",
    tone: "Actionable",
    tags: ["Onboarding", "SaaS", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome to the Product", contentType: "Text + Screenshot" },
      { dayOffset: 1, purpose: "Complete Your Profile", contentType: "Text + Screenshot" },
      { dayOffset: 2, purpose: "Invite Your Team", contentType: "Text" },
      { dayOffset: 4, purpose: "Aha Moment Tutorial", contentType: "Text + Screenshot" },
      { dayOffset: 7, purpose: "Pro Tips", contentType: "Text" },
      { dayOffset: 10, purpose: "Integrations", contentType: "Text + Screenshot" },
      { dayOffset: 14, purpose: "Upgrade to Pro", contentType: "Text" },
    ],
  },
  {
    id: "newsletter-welcome",
    name: "Newsletter Welcome",
    goal: "Engagement",
    emailCount: 3,
    contentTypes: ["Branded"],
    layoutStyle: "Newsletter",
    tone: "Friendly",
    tags: ["Onboarding", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome & What to Expect", contentType: "Branded" },
      { dayOffset: 2, purpose: "Top Content / Resources", contentType: "Branded" },
      { dayOffset: 5, purpose: "Community / Reply Request", contentType: "Branded" },
    ],
  },
  {
    id: "developer-onboarding",
    name: "Developer Onboarding",
    goal: "API Integration",
    emailCount: 5,
    contentTypes: ["Plain Text"],
    layoutStyle: "Terminal",
    tone: "Technical",
    tags: ["Onboarding", "SaaS", "All"],
    emails: [
      { dayOffset: 0, purpose: "API Keys & Docs", contentType: "Plain Text" },
      { dayOffset: 1, purpose: "Make Your First Request", contentType: "Plain Text" },
      { dayOffset: 3, purpose: "SDKs & Libraries", contentType: "Plain Text" },
      { dayOffset: 7, purpose: "Advanced Concepts (Webhooks)", contentType: "Plain Text" },
      { dayOffset: 14, purpose: "Support & Community", contentType: "Plain Text" },
    ],
  },
  {
    id: "ecommerce-saas",
    name: "E-commerce SaaS",
    goal: "Store Setup",
    emailCount: 7,
    contentTypes: ["Text", "Inline Images"],
    layoutStyle: "Visual",
    tone: "Encouraging",
    tags: ["E-commerce", "SaaS", "Onboarding", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome & Connect Store", contentType: "Text + Inline Images" },
      { dayOffset: 1, purpose: "Import Products", contentType: "Text + Inline Images" },
      { dayOffset: 2, purpose: "Customize Theme", contentType: "Text" },
      { dayOffset: 4, purpose: "Set Up Payments", contentType: "Text + Inline Images" },
      { dayOffset: 7, purpose: "Launch Checklist", contentType: "Text" },
      { dayOffset: 10, purpose: "Marketing 101", contentType: "Text" },
      { dayOffset: 14, purpose: "First Sale Celebration", contentType: "Text + Inline Images" },
    ],
  },
  {
    id: "agency-client-onboarding",
    name: "Agency Client Onboarding",
    goal: "Alignment",
    emailCount: 5,
    contentTypes: ["Branded"],
    layoutStyle: "Professional",
    tone: "Professional",
    tags: ["Agency", "Onboarding", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome & Next Steps", contentType: "Branded" },
      { dayOffset: 2, purpose: "Information Gathering Form", contentType: "Branded" },
      { dayOffset: 5, purpose: "Kickoff Call Prep", contentType: "Branded" },
      { dayOffset: 7, purpose: "Meet the Team", contentType: "Branded" },
      { dayOffset: 14, purpose: "Project Timeline", contentType: "Branded" },
    ],
  },
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    goal: "Engagement",
    emailCount: 3,
    contentTypes: ["Text"],
    layoutStyle: "Minimal",
    tone: "Direct",
    tags: ["Onboarding", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome", contentType: "Text" },
      { dayOffset: 3, purpose: "Key Feature", contentType: "Text" },
      { dayOffset: 7, purpose: "Check-in", contentType: "Text" },
    ],
  },
  {
    id: "social-proof-heavy",
    name: "Social Proof Heavy",
    goal: "Trial → Paid",
    emailCount: 5,
    contentTypes: ["Social Proof"],
    layoutStyle: "Testimonial",
    tone: "Persuasive",
    tags: ["Trial conversion", "SaaS", "All"],
    emails: [
      { dayOffset: 0, purpose: "Welcome & Hero Case Study", contentType: "Social Proof" },
      { dayOffset: 3, purpose: "Customer Quote 1 & Feature", contentType: "Social Proof" },
      { dayOffset: 7, purpose: "Customer Quote 2 & ROI", contentType: "Social Proof" },
      { dayOffset: 10, purpose: "Video Testimonial", contentType: "Social Proof" },
      { dayOffset: 13, purpose: "Final Push & Trust Badges", contentType: "Social Proof" },
    ],
  },
  {
    id: "video-first",
    name: "Video-first",
    goal: "Education",
    emailCount: 4,
    contentTypes: ["Video Thumbnail"],
    layoutStyle: "Media",
    tone: "Engaging",
    tags: ["Feature launch", "All"],
    emails: [
      { dayOffset: 0, purpose: "Intro Video", contentType: "Video Thumbnail" },
      { dayOffset: 2, purpose: "Deep Dive Video 1", contentType: "Video Thumbnail" },
      { dayOffset: 5, purpose: "Deep Dive Video 2", contentType: "Video Thumbnail" },
      { dayOffset: 7, purpose: "Live Q&A Recording", contentType: "Video Thumbnail" },
    ],
  },
];
